export { Homepage } from './Home/Homepage'
export { ProductList } from './Products/ProductList'

export { ProductDetails } from './ProductDetails'
export { OrderPage } from './Order/OrderPage'
export { Register } from './Register'
export { Login } from './Login'
export { DashboardPage} from './Dashboard/DashboardPage'
export {CartPage} from './Cart/CartPage'
export { PageNotFound } from './PageNotFound'